services:
  - type: web
    name: jinx-spam-orang
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python index.py
    envVars:
      API_ID: 
        generateValue: true
      API_HASH:
        generateValue: true
      SESSION:
        generateValue: true
      GRUPS:
        generateValue: true
